### ISSUE TITLE
Chrome bed path

### ISSUE THREAD

**Issue by jmrussell** [keoughkath/AcceleratedRegionsNF#2]
Hi,

I am interested in trying this pipeline out on some data I have - but I am unsure how to produce the chrom_bed_path files. Could you provide an example on how that is done? Much appreciated

**Comment by keoughkath** [comment]
Hi - sorry just saw this notification, but also saw the issue is closed. Hope you found everything you need!

**Comment by jmrussell** [comment]
no problem! I was able to figure out file, but I am a little bit confused about the "path to the directory containing BED-formatted (not gzipped) syntenic regions that will be intersected with the phastCons". If my species of interest is a bat, do I just extract each block that contains that species from my maf? I am using the 60 way ucsc MAF as a jumping off point while I get familiar with the workflow.

**Comment by keoughkath** [comment]
Ah, so those are [chain files](https://genome.ucsc.edu/goldenPath/help/chain.html) that are reformatted to BED files that you can use to filter for syntenic regions. A Jupyter notebook showing how to reformat those is [here](https://github.com/keoughkath/AcceleratedRegionsNF/blob/master/bin/format_net_files.ipynb). For example, for HARs I filtered for regions that are syntenic in human, rhesus macaque, dog and mouse. For bat, you could require synteny in a few bat species, or a more distant species like human, depending on your goals.

**Comment by zqlns** [comment]
hi, I previously encountered the same issue as you with the BED file format. Could you please share how you resolved it? I would really appreciate your help!
