### ISSUE TITLE
How long it takes the process to run once？

### ISSUE THREAD

**Issue by liu-wq** [keoughkath/AcceleratedRegionsNF#3]
Hi，

I have a question. For 30 species, how long will it take to complete the whole process?
 For example, using 40 CPUs?

best!
Weiqiang

**Comment by keoughkath** [comment]
Hi Weiqiang, 

It depends on the compute system you're working with, but with 30 species I wouldn't expect it to take overly long. Have you tried it yet?

Kathleen

**Comment by keoughkath** [comment]
Closing due to no response.
