### ISSUE TITLE
The pipeline cannot run successfully

### ISSUE THREAD

**Issue by chun-he-316** [keoughkath/AcceleratedRegionsNF#4]
Hi,
    I have a question. I changed the relative file according to my 
circumstance and ran the command "nextflow run call_ARs_zoo.nf -w "hars_workdir/" -profile local -params-file zoonomia_example_human.yml". As a result, no error was reported, and no corresponding output file was generated. The output is as follows:
N E X T F L O W  ~  version 19.01.0
Launching `call_ARs_zoo.nf` [pensive_lavoisier] - revision: 6dd86da8d4
[warm up] executor > local

The end of the .nextflow.log is as follows:

Jul-23 17:39:21.896 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jul-23 17:39:21.896 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jul-23 17:39:21.896 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jul-23 17:39:21.897 [main] DEBUG nextflow.Session - >>> barrier register (process: multipleTestCorrectionFiltering)
Jul-23 17:39:21.898 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > multipleTestCorrectionFiltering -- maxForks: 112
Jul-23 17:39:21.900 [Actor Thread 2] DEBUG nextflow.Session - <<< barrier arrive (process: multipleTestCorrectionFiltering)
Jul-23 17:39:21.899 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Jul-23 17:39:21.915 [main] DEBUG nextflow.Session - Session await
Jul-23 17:39:21.916 [main] DEBUG nextflow.Session - Session await > all process finished
Jul-23 17:39:22.013 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Jul-23 17:39:22.013 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-23 17:39:22.018 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=0; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms]
Jul-23 17:39:22.027 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Jul-23 17:39:22.079 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

I don't know why the process was not running successfully. Can you tell me how to solve it? Thanks.

Best wishes

**Comment by keoughkath** [comment]
Hello, 

This appears to be a nextflow error, so I would investigate solutions along that route. If more details emerge suggesting the pipeline as the source, please let me know!

Best,
Kathleen
