### ISSUE TITLE
question about species_of_interest

### ISSUE THREAD

**Issue by bighawkin** [keoughkath/AcceleratedRegionsNF#5]
I have some issue about species of interest. The species of interest can put only one species or serveal species? if i want to foucus on a branch of evolution tree ，can i asscess it. Thank you。

**Comment by keoughkath** [comment]
Hello, and sorry for the delayed reply. For species of interest, the pipeline is currently written to support only a single species - to test using these methods on a branch we would need to generate the consensus sequence. I believe you can test acceleration on a branch using HyPhy - hope that helps!
