### ISSUE TITLE
Inquiry about phastCons elements in the 2023 science paper 

### ISSUE THREAD

**Issue by zqlns** [keoughkath/AcceleratedRegionsNF#6]
hi，
I am currently studying your paper titled "Three-dimensional genome rewiring in loci with human accelerated regions" and am particularly intrigued by the enrichment of zooHARs in TADs with hsSVs. I am planning to replace the hsSVs in your study with my own data, and then analyze whether it is enriched with zooHAR in TADs. But the problem is that I can't find phastCons elements anywhere on the Internet. Therefore, I am kindly requesting if you could share the phastCons elements used in your study. Any help or guidance you could provide would be greatly appreciated.
best!

**Comment by keoughkath** [comment]
Hello, and sorry for the delayed reply. In the paper, I identified phastCons elements from the alignment using the PHAST program, which is part of this pipeline. However, you can download phastCons elements from the UCSC genome browser, here: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/phastCons100way/hg38.100way.phastCons/. I hope this helps!
